format = """
$directory $memory_usage(red)
$character """

[character]  
success_symbol = "[](bold green)"
error_symbol = "[](red)"

[memory_usage]
disabled = false
threshold = -1
symbol = ""
format = "[$symbol $ram](red)"
style = "red"
